name: 'notion-jam'
author: victornpb
description: 'A export Notion pages to markdown and images to be used as JAM stack (static website, github pages, eleventy...)'
branding:
  color: gray-dark
  icon: book
inputs:
  GITHUB_TOKEN:
    description: 'GitHub Token'
    required: true
  NOTION_SECRET:
    description: 'Notion API Token secret'
    required: true
  NOTION_DATABASE:
    description: 'Notion Database URL or ID (example: https://notion.so/00112233445566778899aabbccddeeff)'
    required: true
  FILTER_PROP: 
    description: Property on the database used to query pages (default:Status)
    required: false
  FILTER_VALUES:
    description: Return pages with the FILTER_PROP is equal this list of values (default:Ready,Published)
    required: false
  CONVERT_PROP_CASE:
    description: Convert the database property names before adding to the frontmatter (camel,pascal,kebab,snake,none) (default:snake)
    required: false
  ARTICLE_PATH:
    description: 'Path template to where to save markdown files (default="posts/{title}/index.md")'
    required: false
  ASSETS_PATH:
    description: 'Path to save images, if started with . will be relative to ARTICLE_PATH, otherwise absolute (default=".")'
    required: false
  PARALLEL_PAGES:
    description: Fetch this amount of pages in parallel (default=3)'
    required: false
  PARALLEL_DOWNLOADS_PER_PAGE:
    description: 'Number of images to download in parallel for each page (default=3)'
    required: false
  DOWNLOAD_IMAGE_TIMEOUT:
    description: 'Timeout in seconds for each image download (default=30)'
    required: false
  SKIP_DOWNLOADED_IMAGES:
    description: 'Skip downloading images if they already exist in the path (default=true)'
    required: false
  DOWNLOAD_FRONTMATTER_IMAGES:
    description: 'Downloads image urls in the frontmatter'
    required: false

runs:
  
  using: node16
  main: dist/action.mjs
